package com.lauriknuth.tuplausrestapi.models;

import lombok.Getter;

@Getter
public enum CardType {

    ACE_OF_CLUBS("ACE_OF_CLUBS", 1),
    TWO_OF_CLUBS("TWO_OF_CLUBS",2),
    THREE_OF_CLUBS("THREE_OF_CLUBS",3),
    FOUR_OF_CLUBS("FOUR_OF_CLUBS",4),
    FIVE_OF_CLUBS("FIVE_OF_CLUBS",5),
    SIX_OF_CLUBS("SIX_OF_CLUBS",6),
    SEVEN_OF_CLUBS("SEVEN_OF_CLUBS",7),
    EIGHT_OF_CLUBS("EIGHT_OF_CLUBS",8),
    NINE_OF_CLUBS("NINE_OF_CLUBS",9),
    TEN_OF_CLUBS("TEN_OF_CLUBS",10),
    JACK_OF_CLUBS("JACK_OF_CLUBS",11),
    QUEEN_OF_CLUBS("QUEEN_OF_CLUBS",12),
    KING_OF_CLUBS("KING_OF_CLUBS",13),

    ACE_OF_DIAMONDS("ACE_OF_DIAMONDS",1),
    TWO_OF_DIAMONDS("TWO_OF_DIAMONDS",2),
    THREE_OF_DIAMONDS("THREE_OF_DIAMONDS",3),
    FOUR_OF_DIAMONDS("FOUR_OF_DIAMONDS",4),
    FIVE_OF_DIAMONDS("FIVE_OF_DIAMONDS",5),
    SIX_OF_DIAMONDS("SIX_OF_DIAMONDS",6),
    SEVEN_OF_DIAMONDS("SEVEN_OF_DIAMONDS",7),
    EIGHT_OF_DIAMONDS("EIGHT_OF_DIAMONDS",8),
    NINE_OF_DIAMONDS("NINE_OF_DIAMONDS",9),
    TEN_OF_DIAMONDS("TEN_OF_DIAMONDS",10),
    JACK_OF_DIAMONDS("JACK_OF_DIAMONDS",11),
    QUEEN_OF_DIAMONDS("QUEEN_OF_DIAMONDS",12),
    KING_OF_DIAMONDS("KING_OF_DIAMONDS",13),

    ACE_OF_HEARTS("ACE_OF_HEARTS",1),
    TWO_OF_HEARTS("TWO_OF_HEARTS",2),
    THREE_OF_HEARTS("THREE_OF_HEARTS",3),
    FOUR_OF_HEARTS("FOUR_OF_HEARTS",4),
    FIVE_OF_HEARTS("FIVE_OF_HEARTS",5),
    SIX_OF_HEARTS("SIX_OF_HEARTS",6),
    SEVEN_OF_HEARTS("SEVEN_OF_HEARTS",7),
    EIGHT_OF_HEARTS("EIGHT_OF_HEARTS",8),
    NINE_OF_HEARTS("NINE_OF_HEARTS",9),
    TEN_OF_HEARTS("TEN_OF_HEARTS",10),
    JACK_OF_HEARTS("JACK_OF_HEARTS",11),
    QUEEN_OF_HEARTS("QUEEN_OF_HEARTS",12),
    KING_OF_HEARTS("KING_OF_HEARTS",13),

    ACE_OF_SPADES("ACE_OF_SPADES",1),
    TWO_OF_SPADES("TWO_OF_SPADES",2),
    THREE_OF_SPADES("THREE_OF_SPADES",3),
    FOUR_OF_SPADES("FOUR_OF_SPADES",4),
    FIVE_OF_SPADES("FIVE_OF_SPADES",5),
    SIX_OF_SPADES("SIX_OF_SPADES",6),
    SEVEN_OF_SPADES("SEVEN_OF_SPADES",7),
    EIGHT_OF_SPADES("EIGHT_OF_SPADES",8),
    NINE_OF_SPADES("NINE_OF_SPADES",9),
    TEN_OF_SPADES("TEN_OF_SPADES",10),
    JACK_OF_SPADES("JACK_OF_SPADES",11),
    QUEEN_OF_SPADES("QUEEN_OF_SPADES",12),
    KING_OF_SPADES("KING_OF_SPADES",13);

    private final String name;
    private final int value;

    CardType(String name, int value) {
        this.name = name;
        this.value = value;
    }
}
